### ISSUE TITLE
RS latch?

### ISSUE THREAD

**Issue by alfuken** [ivan-hristov/advanced-combinator#54]
Hi, how do I make a working RS latch using this combinator?
I've tried [classical approach](https://wiki.factorio.com/Tutorial:Circuit_network_cookbook#RS_latch_-_single_decider_version) of
<img width="371" alt="Screenshot 2021-10-27 at 11 06 09" src="https://user-images.githubusercontent.com/75377/139035318-9fddbc90-a2f4-4618-95cc-6adaf6d4294c.png">
But it doesn't seem to work at all - the pump just constantly switching on-and-off, but I need it to stay "on" until it drains the tank down to 10k, then shutdown and wait for it to fill up again. Is it possible to set it up properly using this combinator?

**Comment by ivan-hristov** [comment]
Only the input values are used for comparison. The output of the 1st and 2nd checks cannot be used in the 3rd check.

So for example if you want to perform the RS latch you'll need to connect the output to the input using a wire, then you should be able to perform the 3rd check on the next tick.

You can simplify the original example to:
```
Fluid Count > 20k = Output signal
Fluid Count < 10K = Output signal
```
Then the value of the Output signal will be 0 when the fluid count is between 10k and 20k, otherwise the value would be 1

**Comment by alfuken** [comment]
Cool, thanks, I'll have a try at it. Meanwhile, would be nice if this information could be added as a short FAQ to the mod page - i'm sure someone else would probably be looking for something similar, too!
